### ISSUE TITLE
Supports vector as field type

### ISSUE THREAD

**Issue by ghost** [chipsenkbeil/nested-struct#1]
```rust
nested_struct! {
    pub struct MyStruct {
        pub regular_field: Vec<i32>,
        pub nested_field: NestedField {
            pub inner_field: bool
        }
    }
}
```

In the above code, the following error message appears.
no rules expected the token `<`
no rules expected this token in macro call
while trying to match `}`

Could you please support vector as the type?

**Comment by chipsenkbeil** [comment]
@aliaaaasa PRs are welcome!
